version: '2'

services:
  hubot:
    build:
      context: ./hubot
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - HUBOT_SLACK_TOKEN=<slack token | ex) xoxb-....>
      - HUBOT_SLACK_TEAM=<slack team | ex) hogehoge.slack.team>
      - HUBOT_SLACK_BOTNAME=hubot
      - HUBOT_JIRA_URL=<JIRA url | ex) https://... >
      - HUBOT_JIRA_USER=<JIRA user>
      - HUBOT_JIRA_PASSWORD=<JIRA password>
